### PR TITLE
Error handeling

### PR DESCRIPTION
**Pull request by starkillerOG**
- [Reduce code duplication in send function](https://github.com/JimStar/reolink_ip/commit/ffa956e4270b2a0af3169ba9d81e621ecddbdaa0)
- [Retry on 502/Bad Gateway response](https://github.com/JimStar/reolink_ip/commit/facd592f443d4fec21c1b0d965a54bcad7b59e7a)
- [Retry on Json decode error](https://github.com/JimStar/reolink_ip/commit/6d0876122ad53c10cad71b4cfd98e6783f2f0d51)

The 502/Bad Gateway response is disscussed in this HomeAssistant issue: https://github.com/home-assistant/core/issues/84751

Personally I am sometimes experiancing a json decode error when trying to get the host settings.
On the next attempt it always works.
So first try to send the command again before throwing such errors.

### CODE REVIEW

**Comment by starkillerOG** [comment]
@JimStar I have tested this code, and it works.
Could you merge this and release a new version?

**Comment by JimStar** [comment]
The `send()` method optimizations make sense, thank you. I've improved them a little bit more and already merged (locally so far).

But I don't think the dirty workaround of repeating the same request just because the device firmware fails to properly respond sometimes, would be the right thing to do... This is clearly a Reolink bug, among many other bugs their firmware has - for example sometimes it returns some garbage instead of JSON data, sometimes "not logged in" when there is a proper session still active... You can't have a shitload of workarounds, repeating the same requests again and again every time their firmware soiled itself..:) And with what (and how) all this happens in their firmware - by repeating the request you just **lower** the possibility of that bug, but there is still no guarantee it would not happen the second time in row... so what repetition amount you would need to have then to eliminate the bug **completely**, 10?.. 20?.. It would still never be 100%... And it would never guarantee they would not fail with error other than `502` next time... So all these workarounds would just pile and grow up with time, blowing up the code, transferring the responsibility for these bugs from Reolink API code to the consumer code...

IMHO of course, but the right thing to do would be to report a ticket to the Reolink support, and let them fix this bug to eliminate it once and for all. Instead of collecting a shitload of dirty workarounds in the (clean otherwise) consumer/client code...  
BTW, it still might be some user's network issue too - 'cause I have an RLN8-410 myself (with four cameras connected through it), and I've **never** got any of such errors in my log.

In addition - even if that workaround would be used in the consumer library, it actually is not necessary: the periodic 60-seconds update will anyway get back to this same request a minute later after the previous failed, and will eventually update the state, even if the same fail would repeat itself 10 times in row... It would just spend 10 minutes to finally update the state, but it still guarantees that it **eventually** will converge to the updated state. While the proposed "one time repetition" does **not** 100% guarantee that the second repetition would be successful.  
The only difference with current approach - that the user gets **errors** logged. But this is **really** the **bad error**, the camera/NVR firmware bug that needs to be fixed by Reolink. So the logged error in such case is a **good** thing - motivating a user to push at Reolink to fix their bug...

**Comment by JimStar** [comment]
Merged all the optimizations from this PR, with some of my additional improvements...

**Comment by starkillerOG** [comment]
@JimStar thanks for merging the optimizations!

About the retries:

The 502 error happens about once every 72 requests, making a single retry as I proposed would mean the changes of the 502 happening twice would be once every 5184 requests (assuming these 502 errors are random and not correlated).
That would mean having the error once every 4 days compared to once every hour (single retry).
Doing 2 retries would mean having the error once every 260 days instead of once every hour.

About the Json error:
I have seen that one specifically on first connection with the NVR,
```
2023-01-02 12:40:45.871 ERROR (MainThread) [reolink_ip.api] Host nvr.roberts:443: content type error: Error translating JSON response: Expecting value: line 1 column 1 (char 0),  content type 'text/html', data:
U1auCoXnjehnaQz6/pTuA8Ak3PQBcIt1f1FvUfHlGey2bAXGmauWr69gssjy5StHkzXDhRCG2kxtu3DyldrG1bmSx+uAsRB8IZQjJuzT9ldwCo4QNIgIhXv4FwShWQzuwPc0DzZH0r0SEtFiX321Y//+91MR7PXtxBc4ECEbhAFNJ1J4ds1qPWr8dGwUhd18tpfvvoQ=
```
It always starts with the U1, not sure why this is happening...

I do get your opinion about fixing issues that are caused by somthing else, but I also get that it is really really hard for reolink to fix these sporadic errors that might also have to do with the operating enviroment (network etc) of the devices. It is hard for reolink to reproduce these issues (for example you have never seen these issues with the same NVR). If they cannot reproduce, it is also nearly impossible for them to fix the firmware....

Doing a retry is very common in communication, TCP has it build in for when network errors occur. So doing a single retry does not seem strange to me.

**Comment by JimStar** [comment]
Answered [HERE](https://github.com/JimStar/reolink_ip/pull/12#issuecomment-1368890570).

**Pull request closed without merging**
